name: generate-changelog 
description: Create a changelog from Gitea 
inputs:
  gitea_token:
    description: 'Gitea token'
    required: true
outputs:
  output:
    description: 'The output'
    value: ${{ steps.script.outputs.changelog }}

runs:
  using: composite
  steps:
    - name: Install dependencies
      run: pwd; pip3 install httpx
      shell: bash
    - name: Pass inputs to shell
      run: echo "INPUT_NUM=${{ inputs.num }}" >> $GITHUB_ENV
      shell: bash
    - name: run-script
      id: script
      env:
        INPUT_GITEA_TOKEN: ${{ inputs.gitea_token }}
      run: |
        python3 ${{ github.action_path }}/changelog.py
      shell: bash
