name: send-message 
description: Send an alert to Telegram or Rocket Chat 
inputs:
  gitea_token:
    description: 'Gitea token'
    required: true
outputs:
  output:
    description: 'The output'
    value: ${{ steps.script.outputs.changelog }}
  test-action:
    description: 'Test action'
    value: test

runs:
  using: composite
  steps:
    - name: Install dependencies
      run: pwd; pip3 install httpx
      shell: bash
    - name: Pass inputs to shell
      run: echo "INPUT_NUM=${{ inputs.num }}" >> $GITHUB_ENV
      shell: bash
    - name: List files
      run: ls -l $GITHUB_WORKSPACE
      shell: bash
    - name: run-script
      id: script
      run: |
        python3 changelog.py
      shell: bash
