name: send-message 
description: Send an alert to Telegram or Rocket Chat 
inputs:
  gitea-url:
    description: 'Gitea URL in format https://gitea.example.com/Owner/Repo'
    required: true
  base:
    description: 'Branch ref'
    required: true
  gitea-token:
    description: 'Gitea token'
    required: true

runs:
  using: composite
  steps:
    # - name: Install Python
    #   uses: actions/setup-python@v4
    - name: Install dependencies
      run: pip3 install -r requirements.txt
      shell: bash
    # - name: Pass inputs to shell
    #   run: echo "INPUT_NUM=${{ inputs.num }}" >> $GITHUB_ENV
    #   shell: bash
    - name: run-script
      id: script
      run: python3 changelog.py
      shell: bash
