name: Test
description: Test
on:
  push:
    branches:
      - main

jobs:
  test-action:
    runs-on: macOS
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          gitea-url: https://git.lipsar.studio/AL-Mobile-Base/changelog-action
          base: ${{ github.ref }}
          gitea-token: ${{ secrets.GGITEA_TOKEN }}

